name: Build termit

on: [push, pull_request]

jobs:
  ubuntu_latest_build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare build environment.
      run: |
        apt-get update
        apt-get -y install apt-utils
        apt-get -y full-upgrade
        apt-get install -y gcc cmake lua5.4-dev libgtk-3-dev libvte
        echo "missing gtk+3.0 vte libvte"
    - name: Configure
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build
      run: |
        make
    - name: Install
      run: |
        make install
    - name: Test version
      run: |
        termit --version
